MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB
SUPPORTED_FILE_TYPES = ['.csv']
DEFAULT_CORRELATION_METHODS = ['pearson', 'spearman']
MIN_DATA_POINTS = 10
SESSION_TIMEOUT_HOURS = 24
STOCK_DATA_CACHE_MINUTES = 15